# Generated by Django 2.2.5 on 2019-09-28 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
