# Generated by Django 2.2.5 on 2019-09-14 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FitAFApp', '0002_meal_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='user',
            new_name='owner',
        ),
    ]
