# Generated by Django 2.2.5 on 2019-09-29 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitAFApp', '0005_auto_20190928_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='meal_time',
            field=models.TextField(blank=True, null=True),
        ),
    ]
