# Generated by Django 2.2.5 on 2019-09-29 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitAFApp', '0006_meal_meal_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='meal_time',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
    ]
